"""add cover image to projects table

Revision ID: 2ecc9d0fb5fd
Revises: 9cdbf4fc355b
Create Date: 2026-09-14 14:49:11.315891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ecc9d0fb5fd'
down_revision: Union[str, Sequence[str], None] = '9cdbf4fc355b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('cover_image_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'cover_image_url')
    # ### end Alembic commands ###
