"""add tags to projects

Revision ID: 558a4eb93432
Revises: f665c1ca3738
Create Date: 2026-09-14 10:57:24.365072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558a4eb93432'
down_revision: Union[str, Sequence[str], None] = 'f665c1ca3738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('tags', sa.JSON(), nullable=False, server_default="[]"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'tags')
    # ### end Alembic commands ###
