"""add hook to projects

Revision ID: a6f2b117907a
Revises: 72f4aaf668ff
Create Date: 2026-10-04 13:57:18.882799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f2b117907a'
down_revision: Union[str, Sequence[str], None] = '72f4aaf668ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('hook', sa.String(length=300), nullable=False, server_default=""))

    op.alter_column("projects", "hook", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'hook')
    # ### end Alembic commands ###
