"""add highlights to projects

Revision ID: be3cea3a7f71
Revises: 558a4eb93432
Create Date: 2026-09-14 11:15:12.546890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3cea3a7f71'
down_revision: Union[str, Sequence[str], None] = '558a4eb93432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('highlights', sa.JSON(), nullable=False, server_default="[]"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'highlights')
    # ### end Alembic commands ###
